In [ ]:
import numpy as np
import math

In [ ]:
class Neuron():

  def __init__(self,activation):
    self.activation=activation
    self.original_input=0
    self.transformed_input=0
    self.derivative=0

  def forward(self,x):
    self.original_input=x
    self.transformed_input=self.activation(x)
    self.derivative=self.activation.derivative(x)
    return self.transformed_input

  def backprop(self):
    result = self.derivative
    self.transformed_input
    self.derivative
    return result


In [ ]:
class Layer():

  def __init__(self,insize,outsize,activation):
    self.w=np.random.randn(insize, outsize)
    self.b=np.random.randn(outsize)
    self.neuron_list=[Neuron(activation) for i in range(insize)]

  def forward(self,x):
    x=np.array([neuron.forward(x_i) for neuron, x_i in zip(self.neuron_list, x)])
    if self.w.shape[0] > 0:
      x=self.w.T @ x
    return x

  def backward(self,x):
    lr=0.1
    input=np.array([neuron.transformed_input for neuron in self.neuron_list])
    input=input.reshape(-1,1)
    y=(x.reshape(-1,1)).T
    grad_w=np.matmul(input,y)
    grad_b=x
    print('as',self.w,grad_w,input,y,'sa')
    self.w=self.w-lr*grad_w
    self.b=self.b-lr*grad_b
    grad_h=self.w @ x
    neuron_derivatives=np.array([Neuron.derivative for Neuron in self.neuron_list])
    local_derivative=neuron_derivatives*grad_h
    #print(grad_w,grad_b,grad_h,x,neuron_derivatives)
    return local_derivative


  def print_params(self):
    print("Weights (w):")
    print(self.w)
    print("Biases (b):")
    print(self.b)
    for neuron in self.neuron_list:
      print(neuron.orignal_input,neuron.transformed_input,neuron.derivative)

layer=Layer(3,5,Sigmoid())


In [ ]:
class NeuralNetwork():
  def __init__(self,layer_size,Activation):
    #self.layer_tuple=[]
    self.layer_list=[]
    self.current_output=0
    loss_grad=0

    for i in range(len(layer_size)-1):
      j=i+1
      while j<i+2:
        if i==0:
          self.layer_list.append(Layer(layer_size[i],layer_size[j],Linear()))
        elif j==(len(layer_size)):
          self.layer_list.append(Layer(layer_size[i],layer_size[j],Activation))
          self.layer_list.append(Layer(layer_size[j],1,Sigmoid))
        else:
          self.layer_list.append(Layer(layer_size[i],layer_size[j],Activation))
        j+=1

  def Backward(self):
    layer_list_rev=reversed(self.layer_list)
    x=self.loss_grad
    for layer in layer_list_rev:
        x=layer.backward(x)
    return

  def Loss(self,F,x,y):
    loss=F(x,y)
    self.loss_grad=F.derivative(x,y)
    return loss

  def Forward(self,x):
    for layer in self.layer_list:
      x=layer.forward(x)
    self.current_output=x
    return self.current_output
nn=NeuralNetwork([3,2,2],Sigmoid())

In [ ]:
class MSE():
  def __call__(self,x,y):
    if type(x)==int:
      return 0.5*(x-y)**2
    x,y=np.array(x),np.array(y)
    arr=0.5*(x-y)
    arr=arr*arr
    return np.sum(arr)

  def derivative(self,x,y):
    x,y=np.array(x),np.array(y)
    return (x-y)

class CrossEntropy():
  def __call__(self,x,y):
    x=-np.log(x)
    x=x*y
    return np.sum(x)

  def derivative(self,x,y):
    index=np.argmax(y)
    arr=np.zeros(len(y))
    arr[index]=-1/math.log(x[index])
    return arr


In [ ]:
cross=MSE()
print(cross([0.025,0.925,0.025,0.025],[0,1,0,0]))
cross.derivative([0.025,0.925,0.025,0.025],[0,1,0,0])

0.0018749999999999986


array([ 0.025, -0.075,  0.025,  0.025])

In [ ]:
class Sigmoid():
  def __init__(self):
    pass

  def __call__(self,x):
    return 1/(1+np.exp(-x))

  #np.vectorize(compute)

  def derivative(self,x):
    x=self(x)
    return x*(1-x)

class Relu():
  def __call__(self,x):
    x=np.array([i if i > 0 else 0 for i in x])
    return x

  def derivative(self,x):
    x=self(x)
    x=np.array([i if i > 0 else 0 for i in x])
    return x

class Softmax():
  def __call__(self,x):
    return x

class Linear():
  def __call__(self,x):
    return x

  def derivative(self,x):
    x=self(x)
    return x


x=np.array([1,2,3,-1])
sigmoid=Sigmoid()
print(sigmoid(x))
relu=Relu()
relu(x)


[0.73105858 0.88079708 0.95257413 0.26894142]


array([1, 2, 3, 0])

In [ ]:
neuron=Neuron(Sigmoid())
neuron.forward(2)


0.10499358540350662
2 <__main__.Sigmoid object at 0x79482437e170> 0.8807970779778823 0.10499358540350662


In [ ]:
epoch=100
x=[1,2,3]
y=10
for i in range(epoch):
  output=nn.Forward(x)
  nn.Loss(MSE(),output,y)
  nn.Backward()



In [ ]:
x=np.array([1,2,3])
print(nn.Forward(x))

[9.99969231 9.99971663]


In [ ]:
layer.w,layer.b

(array([[ 0.20810048, -0.28010785,  1.26811873, -0.78606315, -0.05226012],
        [ 0.15446202, -0.48820905, -0.32383423,  1.33423334, -0.19400724],
        [-0.43084558,  1.63662684,  0.48777158,  0.3505271 ,  0.31297032]]),
 array([-0.7418632 ,  0.00719553, -0.95316857,  0.55116582, -0.64896796]))

In [ ]:
x,y=np.array([1,2,3]),np.array([1,2,3,4,5])
layer.forward(x)
layer.backward(y)

[[0.73105858 1.46211716 2.19317574 2.92423431 3.65529289]
 [0.88079708 1.76159416 2.64239123 3.52318831 4.40398539]
 [0.95257413 1.90514825 2.85772238 3.81029651 4.76287063]] [1 2 3 4 5] [-3.97413442 -2.27094553  2.03352511] [1 2 3 4 5] [0.19661193 0.10499359 0.04517666]


array([-0.78136225, -0.23843471,  0.09186787])